name: 'My Workflow'

on:
  push:
    brances:
      -main

jobs:
  deploy:
    name: 'Deploy to Netlify'
    steps:
      - uses: actions/checkout@v4
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
          NETLIFY_SITE_ID: ${{ secrets.MY_SITE_ID}}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: dist/axelcars/browser